# Agent配置文件
node_id: 1  # 节点ID
token: "YmIL2Gyhvb-iXC-x-XvsC3yCdxuLr8djN53DWds3YUc="  # 节点认证令牌

# 服务端连接信息
server:
  address: "http://localhost:8080"  # HTTP API地址
  grpc_address: "localhost:8080"    # gRPC服务地址
  tls:
    enabled: false
    ca_cert: ""

# WireGuard配置
wireguard:
  config_path: "/etc/wireguard/"  # WireGuard配置文件路径
  prefix: "wg_"                  # WireGuard配置文件前缀

# Babeld配置
babel:
  config_path: "/etc/babeld/babeld.conf"  # Babeld配置文件路径
  bin_path: "/usr/sbin/babeld"            # babeld命令路径

# 运行时配置
runtime:
  log_path: "data/agent.log"     # 日志文件路径
  log_level: "info"              # 日志级别 (debug, info, warn, error)
  dry_run: true                 # 调试模式
  metrics_port: 9100             # 指标监控端口
