# 服务器配置
server:
  host: "0.0.0.0"
  port: 8080
  tls:
    enabled: false
    cert: "certs/server.crt"
    key: "certs/server.key"
  jwt:
    secret_key: "your-super-secret-key-please-change-in-production"

# 网络配置
network:
  base_port: 36420
  ipv4_range: "10.42.0.0/16"
  ipv4_template: "10.42.{node}.{peer}/32"
  ipv4_node_template: "10.42.{node}.0"
  ipv6_range: "2a13:a5c7:21ff::/48"
  ipv6_template: "2a13:a5c7:21ff:276:{node:x}::{peer:x}/80"
  ipv6_node_template: "2a13:a5c7:21ff:276:{node:x}::"
  link_local_template: "fe80::{node}:{peer}/64"
  link_local_net: "fe80::/64"
  babel_multicast: "ff02::1:6/128"
  babel_port: 6696

# 配置模板
templates:
  wireguard: |
    [Interface]
    PrivateKey = {{ .PrivateKey }}
    ListenPort = {{ .ListenPort }}
    Address = {{ .IPv4Address }}, {{ .IPv6Address }}
    Address = fe80::{{ .NodeID }}:{{ .Peer.ID }}/64
    Table = off
    
    [Peer]
    PublicKey = {{ .Peer.PublicKey }}
    AllowedIPs = 10.42.0.0/16, 2a13:a5c7:21ff::/48
    AllowedIPs = fe80::/64, ff02::1:6/128
    Endpoint = {{ .Peer.Endpoint }}
    PersistentKeepalive = 25

  babel: |
    # Babeld configuration for node {{ .NodeID }}
    local-port {{ .Port }}
    random-id true
    link-detect true
    ipv6-subtrees true

    default type tunnel
    default split-horizon true
    default faraway true
    default unicast true
    
    # Interface configurations
    {{- range .Interfaces }}
    interface {WGPrefix}{{ .Name }} type tunnel
    {{- end }}
    
    ## Import configurations
    # IPv4 routes
    {{- range .IPv4Routes }}
    in ip {{ .Network }}/16 eq 24 allow
    in ip {{ .Network }}/24 eq 32 allow
    {{- end }}
    # IPv6 routes
    {{- range .IPv6Routes }}
    in ip {{ .Network }}/48 eq 80 allow
    in ip {{ .Network }}/80 eq 128 allow
    {{- end }}


    ## Advertise configurations
    # IPv4 routes
    {{- range .IPv4Routes }}
    redistribute ip {{ .Network }}/24 eq 32 allow
    redistribute ip {{ .Network }}/16 eq 24 allow
    redistribute local ip {{ .Network }}/24 eq 32 allow
    {{- end }}
    
    # IPv6 routes
    {{- range .IPv6Routes }}
    redistribute ip {{ .Network }}/48 eq 80 allow
    redistribute ip {{ .Network }}/80 eq 128 allow
    {{- end }}

    redistribute local deny

# 日志配置
log:
  debug: true
  file: "data/mesh-server.log"

# 存储配置
storage:
  type: "postgres"
  sqlite:
    path: "data/mesh.db"
  postgres:
    host: "localhost"
    port: 5432
    user: "meshuser"
    password: "meshpass"
    dbname: "mesh"
    sslmode: "disable"
