name: Makefile CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build_server:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true
        cache-dependency-path: go.sum

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Generate Protocol Files
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        make proto
    
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 9
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
        cache-dependency-path: 'assets/pnpm-lock.yaml'

    - name: Build
      run: make server

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Server
        path: bin/

  build_agent:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true
        cache-dependency-path: go.sum

    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - name: Generate Protocol Files
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        make proto

    - name: Build
      run: make agent

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Agent
        path: bin/
